### ISSUE TITLE
[BUG] 1.14.4 Console Flooding

### ISSUE THREAD

**Issue by Osprey4444** [ErdbeerbaerLP/Discord-Chat-Integration#53] opened 2020-04-07 20:42 UTC
**What happened?**
- Console Being Flooded

**What should happen?**
- No Console Flooding, doesn't flood my 1.12.2 server's.

**Steps to reproduce**
- Not sure.

**Version**
- 1.14

Mod version _0.0.0_

**Config file**
-https://paste.dimdev.org/ukinutucem.bash

- What is flooded in console - https://hastebin.com/cowuhutuwu.css  

**Additional info**

-

**Comment by ErdbeerbaerLP** [comment] 2020-04-08 07:52
Duplicate of #52

**Closed by ErdbeerbaerLP** 2020-04-08 07:52 UTC
Labels: bug
