### ISSUE TITLE
[BUG-1.16.1] Stopping server doesn't actually stop it. (server hangs.) (read desc)

### ISSUE THREAD

**Issue by Gbergz** [ErdbeerbaerLP/Discord-Chat-Integration#85] opened 2020-07-08 14:12 UTC
**What happened?**
- Trying to stop the server and it doesn't actually stop.

**What should happen?**
- Server stops as it should normally.

**Steps to reproduce**
- Have DCIntegration hooked up to a bot and is connected to a chat in Discord.
- Stop the server and it hangs for a couple of minutes.

**Version**
- 1.16.1

Mod version _1.3.1_

**Config file**
- https://hastebin.com/nucuhejexu.shell

**Crash report if available. No Crash but some Logs;**
Console Log:
- https://hastebin.com/gimigilipu.cs

**Comment by ErdbeerbaerLP** [comment] 2020-07-08 18:56
Duplicate of #58

**Closed by ErdbeerbaerLP** 2020-07-08 18:56 UTC
Labels: bug

**Comment by Gbergz** [comment] 2020-07-11 13:19
So looking through that issue, there appears to be no fix?

**Comment by ErdbeerbaerLP** [comment] 2020-07-11 13:19
Not yet, no

**Comment by Gbergz** [comment] 2020-07-11 23:55
So by actually just disabling the "Server Stopped & Server Started, Server Starting.." messages, (making them blank). The server Hang doesn't happen anymore. It just throws an error in console because of the messages being blank but it still works like normal.
https://hastebin.com/uduzakufic.pl
