### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by koderian** [ErdbeerbaerLP/Discord-Chat-Integration#121] opened 2020-10-11 20:34 UTC
**What happened?**
-With Discord Integration installed, my Forge 1.15.2 (31.2.45) server hangs when trying to restart. I try to restart the server, however it just hangs. I have singled it out to be specifically `dcintegration-1.1.14-1.15`, as without the plugin, the server successfuly restarts without having to force kill it.

**What should happen?**
-It prevents the server from succesfully restarting and stopping

**Steps to reproduce**
- Have a Forge 1.15.2 31.2.45 Server
- Install `dcintegration-1.1.14-1.15`
- Try to restart server.

Demonstration of what happens WITH the mod installed in the mods folder: [https://i.imgur.com/A9zvzjI.gif](https://i.imgur.com/A9zvzjI.gif)

**Version**
-
- [ ] 1.12
- [ ] 1.14
- [X ] 1.15

Mod version _0.0.0_

**Config file**
-https://paste.ubuntu.com/p/gbQtYFDvjm/
*REMOVE YOUR BOT TOKEN BEFORE UPLOADING!!!*

**Crash report if available (use https://paste.dimdev.org)**
-Here is a video that shows the server successfully restarts/stops without having to kill it (this is WITHOUT the mod installed):
https://streamable.com/pqo631

-Here is a video that shows the server does NOT successfully restart/stop without having to kill it (this is WITH the mod **installed):**
https://streamable.com/ily96j

**Additional info**

- I just really want this to work

**Comment by ErdbeerbaerLP** [comment] 2020-10-15 12:14
Duplicate of #58

**Closed by ErdbeerbaerLP** 2020-10-15 12:14 UTC
Labels: bug, duplicate
