### ISSUE TITLE
[BUG] Server hangs on shutdown

### ISSUE THREAD

**Issue by MilkMC** [ErdbeerbaerLP/Discord-Chat-Integration#58] opened 2020-04-25 06:11 UTC
**What happened?**
- When I use the command **/stop** soon after starting the server it says it saves all chunks, but then it "hangs" until 5 minutes have passed since the server started. If I wait at least 5 minutes and then do the command, the server shuts down normally.

Edit: Sometimes it may occur even after the server has been running for a long time. Exact circumstances to cause this are unknown.

**What should happen?**
- The server should be able to shut down normally even after it just started. I know this is not a usual server use case, but this is a test server for a new 1.15.2 mod and I'm restarting often to make small adjustments.

**Steps to reproduce**
- Run the mod version 1.1.13 with forge 31.1.27 for Minecraft 1.15.2
- Do **/stop** right after the server starts.

**Version**
-
- [ ] 1.12
- [ ] 1.14
- [✓] 1.15.2

Mod version 1.1.13

**Config file**
- Default file, no changes were made.

**Additional info**

- I've been using 1.7.10 for years but this is my first experience in 1.15 so I might just be doing something wrong.

**Logs**
This first set of logs is when I shutdown the server as soon as it has started.
[debug-1.log](https://github.com/ErdbeerbaerLP/Discord-Chat-Integration/files/4532445/debug-1.log)
[restart-1.txt](https://github.com/ErdbeerbaerLP/Discord-Chat-Integration/files/4532446/restart-1.txt)

This second set of logs is when I wait 5 minutes or so before shutting down the server.
[debug-2.log](https://github.com/ErdbeerbaerLP/Discord-Chat-Integration/files/4532453/debug-2.log)
[restart-2.txt](https://github.com/ErdbeerbaerLP/Discord-Chat-Integration/files/4532454/restart-2.txt)

This is the startup script I am using. File Extension changed from **sh** to **txt** for upload.
[start.txt](https://github.com/ErdbeerbaerLP/Discord-Chat-Integration/files/4532455/start.txt)

**Comment by Siiriiks** [comment] 2020-04-26 02:14
I'm getting this exact same issue using Minecraft 1.14.4 with version 1.1.14 except it doesn't matter for how long the server has been running for and it will stay paused until I kill java. The issue only showed up as soon as I downloaded this mod, although it's a great mod, very nice job btw :). I am running Forge version 28.2.0 (Recommended).

**Comment by MilkMC** [comment] 2020-05-27 00:24
Can this get fixed?

**Comment by ErdbeerbaerLP** [comment] 2020-05-27 06:57
I am unable to reproduce this bug and the log files also seem to not show any errors. I only have one idea: disable the shutdown message by setting it blank (1.15/1.12 only). If it fixes that it might be caused by how I force the message to be sent before server actually stops

**Comment by MilkMC** [comment] 2020-05-27 09:09
I changed this line in the config to be as shown:

	msgServerStopped = ""

But I get a crash saying that it can't be empty. Interestingly, the server still hangs after it crashes which is not the behavior I would expect, but perhaps this can help narrow down the cause.
[crash-2020-05-27_08.38.03-server.txt](https://github.com/ErdbeerbaerLP/Discord-Chat-Integration/files/4687728/crash-2020-05-27_08.38.03-server.txt)

**Comment by ErdbeerbaerLP** [comment] 2020-05-27 10:35
I think I found it. I tested using Linux and it had the delay

**Comment by Tander** [comment] 2020-05-31 13:26
Oh, actually, I have the same problem on my server. Removing this mod helped. Ping me if you need any information about my setup.

**Comment by Tander** [comment] 2020-06-01 14:41
A-ha! I think I caught that. `botModifyDescription = false` fixed the issue for me it seems. But i'm not sure, need more testing.

**Comment by MilkMC** [comment] 2020-06-01 16:30
That didn't seem to fix it for me. But if you have a working config, please send it (excluding your bot token and channel).

**Comment by Tander** [comment] 2020-06-01 17:03
https://pastebin.com/M3Q3CeXm (it's from my recent bugreport https://github.com/ErdbeerbaerLP/Discord-Chat-Integration/issues/72 )
Just change `botModifyDescription` to `false` in it.

**Comment by MilkMC** [comment] 2020-06-01 17:51
I copied your config, changed that line to false, and updated to version 1.2.5 but it's still hanging on shutdown.

**Comment by ErdbeerbaerLP** [comment] 2020-06-01 17:54
It is some weird issue with Linux.
Testing using windows cmd: no problems.
Testing using windows subsystem for linux (Ubuntu) I get that.
Not tested on other Linux versions tho

**Comment by MilkMC** [comment] 2020-06-01 18:18
Yeah, I'm on Ubuntu 18.04.4 LTS.

**Comment by Tander** [comment] 2020-06-01 20:15
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
```
```
$ java -version
java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)
```

You may find my list of mods in crashlog in https://github.com/ErdbeerbaerLP/Discord-Chat-Integration/issues/72

**Comment by Tander** [comment] 2020-06-02 14:02
Yes, can confirm: `botModifyDescription = false` fixed this issue for me. Server just made full cycle (stop - backup - start - working for 12 hours - stop) without any actions from my side. So probably my issue wasn't a part of MilkMC's one, just similar symptoms.

Since `botModifyDescription` helped for me, I guess my case was a part of #70 instead? Still hope it will be fixed, I liked botModifyDescription feature.

**Comment by ErdbeerbaerLP** [comment] 2020-06-02 14:03
Maybe they change it back when this post gets enough upvotes.
https://support.discord.com/hc/en-us/community/posts/360067755532-Increase-rate-limit-for-editing-channel-description

**Comment by Tander** [comment] 2020-06-03 06:58
And it hung up again. But with new errors this time.
```
> stop
[04:07:12] [Server thread/INFO] [minecraft/DedicatedServer]: Stopping the server
[04:07:12] [Server thread/INFO] [co.sk.wo.ex.pl.PlatformManager/]: Unregistering com.sk89q.worldedit.forge.ForgePlatform from WorldEdit
[04:07:12] [Server thread/WARN] [environmentalcreepers/]: Invalid entity class name (class not found): 'appeng.entity.EntitySingularity'
[04:07:12] [Server thread/WARN] [environmentalcreepers/]: Invalid explosion class name (class not found): 'slimeknights.tconstruct.gadgets.entity.ExplosionEFLN'
[04:07:12] [Server thread/INFO] [thutessentials/]: Server Stopped
[04:07:12] [Server thread/INFO] [simplelogin/]: Shutting down player login handler
[04:07:12] [Server thread/INFO] [simplelogin/]: Saving all entries
[04:07:12] [Server thread/INFO] [minecraft/MinecraftServer]: Stopping server
[04:07:12] [Server thread/INFO] [minecraft/MinecraftServer]: Saving players
[04:07:12] [Server thread/INFO] [minecraft/MinecraftServer]: Saving worlds
[04:07:12] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'world'/minecraft:overworld
[04:07:13] [Server thread/INFO] [minecraft/ChunkManager]: ThreadedAnvilChunkStorage (world): All chunks are saved
[04:07:13] [Server thread/INFO] [minecraft/ChunkManager]: ThreadedAnvilChunkStorage (world): All chunks are saved
[04:07:13] [Thread-1/ERROR] [ne.mi.fm.ja.FMLModContainer/]: Exception caught during firing event: null
        Index: 1
        Listeners:
                0: LOWEST
                1: ASM: class ovh.corail.flying_things.config.ConfigFlyingThings$ConfigEvent onReloadConfig(Lnet/minecraftforge/fml/config/ModConfig$Reloading;)V
java.lang.NullPointerException
        at net.minecraftforge.fml.LogicalSidedProvider.lambda$static$3(LogicalSidedProvider.java:33)
        at net.minecraftforge.fml.LogicalSidedProvider.get(LogicalSidedProvider.java:60)
        at ovh.corail.flying_things.proxy.ServerProxy.markConfigDirty(ServerProxy.java:24)
        at ovh.corail.flying_things.config.ConfigFlyingThings$ConfigEvent.onReloadConfig(ConfigFlyingThings.java:224)
        at net.minecraftforge.eventbus.ASMEventHandler_65_ConfigEvent_onReloadConfig_Reloading.invoke(.dynamic)
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
        at net.minecraftforge.fml.javafmlmod.FMLModContainer.lambda$new$0(FMLModContainer.java:66)
        at net.minecraftforge.fml.ModContainer.lambda$dispatchConfigEvent$5(ModContainer.java:147)
        at java.util.Optional.ifPresent(Optional.java:159)
        at net.minecraftforge.fml.ModContainer.dispatchConfigEvent(ModContainer.java:147)
        at net.minecraftforge.fml.config.ModConfig.fireEvent(ModConfig.java:89)
        at net.minecraftforge.fml.config.ConfigFileTypeHandler$ConfigWatcher.run(ConfigFileTypeHandler.java:104)
        at com.electronwill.nightconfig.core.file.FileWatcher$WatcherThread.run(FileWatcher.java:181)

[04:07:13] [Thread-1/INFO] [STDERR/]: [com.electronwill.nightconfig.core.file.FileWatcher$WatcherThread:run:183]: java.lang.NullPointerException
[04:07:13] [Thread-1/INFO] [STDERR/]: [com.electronwill.nightconfig.core.file.FileWatcher$WatcherThread:run:183]:         at net.minecraftforge.fml.LogicalSidedProvider.lambda$static$3(LogicalSidedProvider.java:33)
[04:07:13] [Thread-1/INFO] [STDERR/]: [com.electronwill.nightconfig.core.file.FileWatcher$WatcherThread:run:183]:         at net.minecraftforge.fml.LogicalSidedProvider.get(LogicalSidedProvider.java:60)
[04:07:13] [Thread-1/INFO] [STDERR/]: [com.electronwill.nightconfig.core.file.FileWatcher$WatcherThread:run:183]:         at ovh.corail.flying_things.proxy.ServerProxy.markConfigDirty(ServerProxy.java:24)
[04:07:13] [Thread-1/INFO] [STDERR/]: [com.electronwill.nightconfig.core.file.FileWatcher$WatcherThread:run:183]:         at ovh.corail.flying_things.config.ConfigFlyingThings$ConfigEvent.onReloadConfig(ConfigFlyingThings.java:224)
[04:07:13] [Thread-1/INFO] [STDERR/]: [com.electronwill.nightconfig.core.file.FileWatcher$WatcherThread:run:183]:         at net.minecraftforge.eventbus.ASMEventHandler_65_ConfigEvent_onReloadConfig_Reloading.invoke(.dynamic)
[04:07:13] [Thread-1/INFO] [STDERR/]: [com.electronwill.nightconfig.core.file.FileWatcher$WatcherThread:run:183]:         at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
[04:07:13] [Thread-1/INFO] [STDERR/]: [com.electronwill.nightconfig.core.file.FileWatcher$WatcherThread:run:183]:         at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
[04:07:13] [Thread-1/INFO] [STDERR/]: [com.electronwill.nightconfig.core.file.FileWatcher$WatcherThread:run:183]:         at net.minecraftforge.fml.javafmlmod.FMLModContainer.lambda$new$0(FMLModContainer.java:66)
[04:07:13] [Thread-1/INFO] [STDERR/]: [com.electronwill.nightconfig.core.file.FileWatcher$WatcherThread:run:183]:         at net.minecraftforge.fml.ModContainer.lambda$dispatchConfigEvent$5(ModContainer.java:147)
[04:07:13] [Thread-1/INFO] [STDERR/]: [com.electronwill.nightconfig.core.file.FileWatcher$WatcherThread:run:183]:         at java.util.Optional.ifPresent(Optional.java:159)
[04:07:13] [Thread-1/INFO] [STDERR/]: [com.electronwill.nightconfig.core.file.FileWatcher$WatcherThread:run:183]:         at net.minecraftforge.fml.ModContainer.dispatchConfigEvent(ModContainer.java:147)
[04:07:13] [Thread-1/INFO] [STDERR/]: [com.electronwill.nightconfig.core.file.FileWatcher$WatcherThread:run:183]:         at net.minecraftforge.fml.config.ModConfig.fireEvent(ModConfig.java:89)
[04:07:13] [Thread-1/INFO] [STDERR/]: [com.electronwill.nightconfig.core.file.FileWatcher$WatcherThread:run:183]:         at net.minecraftforge.fml.config.ConfigFileTypeHandler$ConfigWatcher.run(ConfigFileTypeHandler.java:104)
[04:07:13] [Thread-1/INFO] [STDERR/]: [com.electronwill.nightconfig.core.file.FileWatcher$WatcherThread:run:183]:         at com.electronwill.nightconfig.core.file.FileWatcher$WatcherThread.run(FileWatcher.java:181)
```

**Comment by ErdbeerbaerLP** [comment] 2020-06-03 06:59
That is a different mod

**Comment by Tander** [comment] 2020-06-03 07:10
Yeah, but it's weird: I haven't update this mod when my issue was started, and new error says that is something wrong with config, but I haven't changed it either.

**Comment by McKitten** [comment] 2020-06-24 18:28
Servers are running CentOS and getting this in the server output AFTER the server does it shutdown save on both 1.14.4 & 1.15.2 most current versions

https://pastebin.com/qx51GT4K

Knocks it out for about 6minutes without fail. 
Wouldn't be looking for a library that isn't available publicly would it?

**Comment by Tander** [comment] 2020-06-24 21:26
Just for the record: my problem was irrelevant to this ticket. I updated mods in the pack a couple of weeks ago and it works without any issues now.

**Comment by katubug** [comment] 2020-07-11 22:16
I am having this issue as well on 1.15.2, Forge 31.2.30. DCIntegration 1.3.1.

I think this may also be related to my players timing out? Someone will get booted and then no one will be able to connect until I kill and restart the server. I've also found this in my log, usually at the same time the timeout happens:

```
>....Exception in thread "Thread-73" [15:10:20] [Thread-73/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.IllegalArgumentException: ID may not be null
>.... [15:10:20] [Thread-73/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: at net.dv8tion.jda.internal.utils.Checks.notNull(Checks.java:56)
>.... [15:10:20] [Thread-73/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: at net.dv8tion.jda.internal.utils.Checks.notEmpty(Checks.java:61)
>.... [15:10:20] [Thread-73/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: at net.dv8tion.jda.api.utils.MiscUtil.parseSnowflake(MiscUtil.java:105)
>.... [15:10:20] [Thread-73/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: at net.dv8tion.jda.api.utils.cache.SnowflakeCacheView.getElementById(SnowflakeCacheView.java:59)
>.... [15:10:20] [Thread-73/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: at net.dv8tion.jda.api.JDA.getUserById(JDA.java:539)
>.... [15:10:20] [Thread-73/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: at de.erdbeerbaerlp.dcintegration.DiscordIntegration.lambda$playerJoin$0(DiscordIntegration.java:170)
>.... [15:10:20] [Thread-73/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: at java.lang.Thread.run(Thread.java:748)
```

**Comment by ErdbeerbaerLP** [comment] 2020-07-11 22:26
Oh, forgot an null check :/
Will fix that one in the next update. But that error is not relevant to the shutdown problem, as the code is newer than the issue

**Comment by katubug** [comment] 2020-07-11 22:28
Ah okay, good to know. Thanks! If I can get any more information to you about the shutdown issue, let me know! I'm happy to help out if I can.

**Comment by katubug** [comment] 2020-07-21 01:49
Just wanted to update for my case - the shutdown hang was caused by LagMeter. Removing that mod made my server able to shut down normally again. It does still stall out sometimes, though. Unsure if that's related.

**Comment by LemADEC** [comment] 2020-07-28 19:50
Server is hanging on shutdown just after this callstack while using version 1.3.2-1.15
```
[05:35:43] [JDA MainWS-ReadThread/INFO] [STDERR]: [net.dv8tion.jda.internal.utils.SimpleLogger:write:277]: [JDA MainWS-ReadThread] ERROR WebSocketClient - There was an error in the WebSocket connection
[05:35:43] [JDA MainWS-ReadThread/INFO] [STDERR]: [net.dv8tion.jda.internal.utils.SimpleLogger:log:272]: java.lang.NoClassDefFoundError: net/dv8tion/jda/api/requests/CloseCode
[05:35:43] [JDA MainWS-ReadThread/INFO] [STDERR]: [net.dv8tion.jda.internal.utils.SimpleLogger:log:272]:        at net.dv8tion.jda.internal.requests.WebSocketClient.onDisconnected(WebSocketClient.java:384)
[05:35:43] [JDA MainWS-ReadThread/INFO] [STDERR]: [net.dv8tion.jda.internal.utils.SimpleLogger:log:272]:        at dcshadow.com.neovisionaries.ws.client.ListenerManager.callOnDisconnected(ListenerManager.java:224)
[05:35:43] [JDA MainWS-ReadThread/INFO] [STDERR]: [net.dv8tion.jda.internal.utils.SimpleLogger:log:272]:        at dcshadow.com.neovisionaries.ws.client.WebSocket.finish(WebSocket.java:3730)
[05:35:43] [JDA MainWS-ReadThread/INFO] [STDERR]: [net.dv8tion.jda.internal.utils.SimpleLogger:log:272]:        at dcshadow.com.neovisionaries.ws.client.WebSocket.onThreadsFinished(WebSocket.java:3696)
[05:35:43] [JDA MainWS-ReadThread/INFO] [STDERR]: [net.dv8tion.jda.internal.utils.SimpleLogger:log:272]:        at dcshadow.com.neovisionaries.ws.client.WebSocket.onReadingThreadFinished(WebSocket.java:3663)
[05:35:43] [JDA MainWS-ReadThread/INFO] [STDERR]: [net.dv8tion.jda.internal.utils.SimpleLogger:log:272]:        at dcshadow.com.neovisionaries.ws.client.ReadingThread.notifyFinished(ReadingThread.java:1138)
[05:35:43] [JDA MainWS-ReadThread/INFO] [STDERR]: [net.dv8tion.jda.internal.utils.SimpleLogger:log:272]:        at dcshadow.com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:80)
[05:35:43] [JDA MainWS-ReadThread/INFO] [STDERR]: [net.dv8tion.jda.internal.utils.SimpleLogger:log:272]:        at dcshadow.com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
[05:35:43] [JDA MainWS-ReadThread/INFO] [STDERR]: [net.dv8tion.jda.internal.utils.SimpleLogger:write:279]: Caused by: java.lang.ClassNotFoundException: net.dv8tion.jda.api.requests.CloseCode
[05:35:43] [JDA MainWS-ReadThread/INFO] [STDERR]: [net.dv8tion.jda.internal.utils.SimpleLogger:write:279]:      at java.lang.ClassLoader.findClass(ClassLoader.java:523)
[05:35:43] [JDA MainWS-ReadThread/INFO] [STDERR]: [net.dv8tion.jda.internal.utils.SimpleLogger:write:279]:      at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
[05:35:43] [JDA MainWS-ReadThread/INFO] [STDERR]: [net.dv8tion.jda.internal.utils.SimpleLogger:write:279]:      at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:101)
[05:35:43] [JDA MainWS-ReadThread/INFO] [STDERR]: [net.dv8tion.jda.internal.utils.SimpleLogger:write:279]:      at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
[05:35:43] [JDA MainWS-ReadThread/INFO] [STDERR]: [net.dv8tion.jda.internal.utils.SimpleLogger:write:279]:      ... 8 more
```
1.2.7-1.15#69 was showing a similar error at shutdown.

**Comment by KevinLinders1904** [comment] 2020-07-31 14:33
I have the same problem on ubunto 18.04.4 This seems to be a major issue on linux?

**Comment by khloroshue** [comment] 2020-08-10 23:19
Having the same issue here. Doesn't seem to matter how long the server has been running. Experiencing the same issue running on a VPS as well. My home machine encounters the issue and is using the following versions:
- Windows 10 x64 1909
- Java 1.8.0_261
- Forge 1.16.1-32.0.108
- DiscordIntegration v. 1.3.3 - 1.16.

**Comment by ErdbeerbaerLP** [comment] 2020-08-11 06:35
OK. Then it seems to not be an Linux specific issue. I just can't reproduce it on windows. 🤔

**Comment by khloroshue** [comment] 2020-08-14 20:56
I suspect this is an issue on Discord's end - I don't know if it's holding a socket open on their end or something, but I've tried several mods that hook into discord, and the issue exists on every mod I've tried. Maybe it's a result of rate limiting or something of the like that they've implemented to deal with load.

**Comment by Ki-Tan2934** [comment] 2020-09-15 18:20
Was a fix ever found?

**Comment by ErdbeerbaerLP** [comment] 2020-09-16 09:17
Currently not, no :/

**Comment by Ki-Tan2934** [comment] 2020-09-16 11:42
Maybe add a way for Rcon to force stop DC intergrations before /stop is used
For example /Dstop (kills discord bot) Wait 10s - /stop

**Comment by Ki-Tan2934** [comment] 2020-09-16 11:44
Or implement a new command that kills the mod before the server closes could even be an additional mod call DCFIX-Linux

**Comment by TymonU** [comment] 2020-09-27 18:14
Same problem here. I think it has to do with checking for possible server crash. The discord plugin I am using from sponge on my old world only watches for the stop command.

**Comment by Ki-Tan2934** [comment] 2020-10-08 20:07
Was there ever a fix? 1.16.3 does the same all I really want is discord chat and nothing more
1.12.2 Minecraft does not have a problem

**Comment by ErdbeerbaerLP** [comment] 2020-10-08 20:56
Finally got some time, so I planned to do an half-rewrite of this mod to add new features and fix bugs. Maybe this bug vanishes too then. Also *leak* I plan on doing an spigot port of this mod

**Comment by Ki-Tan2934** [comment] 2020-10-09 00:37
Sounds good

**Comment by Ki-Tan2934** [comment] 2020-10-10 13:30
I can test on Linux if you want

**Comment by Ki-Tan2934** [comment] 2020-10-10 14:50
Could you add a /discord stop command

**Comment by Ki-Tan2934** [comment] 2020-10-10 20:53
I did manage to get a crashlog don't think it'll help https://paste.ubuntu.com/p/rwwHCksSKF/

To crash just do /discord restart then /stop right after

**Comment by koderian** [comment] 2020-10-11 21:46
Same problem, I just opened a issue with some details

**Comment by sfPlayer1** [comment] 2020-10-31 23:04
I noticed a couple non-daemon okhttp threads, which may be the root cause behind this. While those threads may have a way to be orderly terminated, this wouldn't be possible in a crash.

https://github.com/square/okhttp/pull/5834 fixes this original issue, but JDA itself is still on okhttp 3.13 and would need to update...

**Comment by ErdbeerbaerLP** [comment] 2020-11-01 16:32
Ok, will include the new okhttp version in the next update. Just tested replacing the version of JDA with the latest one and it works AND fixes this problem!

**Closed** 2020-11-01 22:20 UTC
Labels: bug, high priority
